version: 2

models:
  - name: stg_accounts
    description: "Cleaned/typed staging model for accounts."
    columns:
      - name: account_id
        description: "Primary key for the account."
        tests:
          - not_null
          - unique

      - name: plan_tier
        description: "Subscription plan tier (e.g., free, basic, pro, enterprise)."
        tests:
          - not_null

      - name: created_at
        description: "Timestamp when the account was created."
        tests:
          - not_null
  - name: stg_users
    description: "Cleaned/typed staging model for users."
    columns:
      - name: user_id
        description: "Primary key for the user."
        tests:
          - not_null
          - unique

      - name: account_id
        description: "FK to stg_accounts.account_id"
        tests:
          - not_null
          - relationships:
              to: ref('stg_accounts')
              field: account_id

      - name: created_at
        description: "Timestamp when the user record was created."
        tests:
          - not_null
  - name: stg_events
    description: "Cleaned/typed staging model for atomic events."
    columns:
      - name: event_id
        description: "Primary key for the event."
        tests:
          - not_null
          - unique

      - name: user_id
        description: "FK to stg_users.user_id"
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_id

      - name: account_id
        description: "FK to stg_accounts.account_id."
        tests:
          - not_null
          - relationships:
              to: ref('stg_accounts')
              field: account_id

      - name: event_ts
        description: "When the event happened."
        tests:
          - not_null

      - name: ingested_at
        description: "When the event was received."
        tests:
          - not_null

      - name: source
        description: "Event source platform."
        tests:
          - accepted_values:
              values: ['desktop', 'web', 'mobile', 'api']
              quote: true
