version: 2

models:
  - name: mart_account_daily_health
    description: "Account-day executive health mart: usage, engagement, productivity, and data trust signals."
    columns:
      - name: event_date
        description: "Account-day date (from dim_user_day.date_day)."
        tests: [not_null]

      - name: account_id
        description: "Account identifier."
        tests: [not_null]

      - name: account_name
        description: "Account display name."
        tests: [not_null]

      - name: plan_tier
        description: "Plan tier of the account (e.g., free, pro)."

      - name: region
        description: "Geographic region of the account."

      - name: is_active
        description: "Whether the account is active."
        tests: [not_null]

      - name: eligible_users
        description: "Count of eligible users for the account-day."
        tests: [not_null]

      - name: dau
        description: "Daily active users (distinct users with activity)."
        tests: [not_null]

      - name: adoption_rate
        description: "DAU / eligible_users; fraction of eligible users active that day."
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1

      - name: engagement_per_active_user
        description: "Engagement events per active user."
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: sessions_started_per_active_user
        description: "Sessions started per active user."
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: work_min_per_active_user
        description: "Total work minutes per active user."
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: tasks_completed_per_active_user
        description: "Tasks completed per active user."
        tests:
          - dbt_utils.accepted_range:
              min_value: 0

      - name: late_event_rate
        description: "Rate of late events relative to activity signals."
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 1

    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns: [account_id, event_date]
